---
# This Playbook will install php-fpm and the required components

- name: Install php
  yum: name={{ item }} state=installed
  with_items:
   - php-cli
   - php-fpm
   - php-apc
   - php-gd
   - php-redis
   - php-mysql
   - php-dom
  notify:
    - start php-fpm

- name: Setup php_fpm
  ini_file: dest=/etc/php-fpm.d/www.conf
    section=www
    option=${item.key}
    value=${item.value}
    backup=yes
  with_items:
    - $php_fpm
  notify:
    - restart php-fpm

- name: Setup php.ini
  ini_file: dest=/etc/php.ini
    section=PHP
    option=${item.key}
    value=${item.value}
    backup=yes
  with_items:
    - $php_ini
  notify:
    - restart php-fpm
    