---
# This Playbook will install nginx

- name: Create the MariaDB Repository.
  copy: src=MariaDB.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo

- name: Install MariaDB
  yum: name={{ item }} state=installed
  with_items:
   - MariaDB-server
   - MariaDB-client
   - MariaDB-shared

- name: Install extra libraries
  yum: name={{ item }} state=installed
  with_items:
   - MySQL-python

- name: Start the MySQL service
  action: service name=mysql state=started