---
# This Playbook will install nginx

- name: Install nginx
  yum: name={{ item }} state=installed
  with_items:
   - nginx12
  notify:
    - start nginx

- name: Copy nginx configurations
  copy: src={{ item }} dest=/etc/nginx/conf.d/ owner=nginx group=nginx mode=644
  with_fileglob:
    - conf.d/*.conf
  notify:
    - reload nginx

- name: Provision nginx templated configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=nginx group=nginx mode=644
  notify:
    - reload nginx

- name: Ensure /etc/nginx/sites exists
  file: path=/etc/nginx/sites state=directory owner=nginx group=nginx mode=644

- name: Provision nginx vhost templated configuration
  template: src=sites/default.conf.j2 dest=/etc/nginx/sites/default.conf owner=nginx group=nginx mode=644
  notify:
    - reload nginx

- name: Allow port 80 iptables 
  lineinfile: dest=/etc/sysconfig/iptables
    regexp="^-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ nginx_port }} -j ACCEPT"
    state=present
    insertbefore='-A INPUT -p tcp'
    line="-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ nginx_port }} -j ACCEPT"
  notify:
    - restart iptables

