---
# This Playbook will install nginx

- name: Install nginx
  yum: name={{ item }} state=installed
  with_items:
   - nginx12

- name: Copy nginx configurations
  copy: src={{ item }} dest=/etc/nginx/conf.d/ owner=nginx group=nginx mode=644
  with_fileglob:
    - conf.d/*.conf

- name: Provision nginx templated configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=nginx group=nginx mode=644

- name: Ensure /etc/nginx/sites exists
  shell: mkdir -p /etc/nginx/sites

- name: Provision nginx vhost templated configuration
  template: src=sites/default.conf.j2 dest=/etc/nginx/sites/default.conf owner=nginx group=nginx mode=644

- name: Allow traffic to the nginx port
  shell: /bin/grep -c {{ nginx_port }} /etc/sysconfig/iptables || /sbin/iptables -I INPUT 4 -p tcp -m state --state NEW -m tcp --dport {{ nginx_port }} -j ACCEPT && /sbin/iptables-save > /etc/sysconfig/iptables
  notify:
    - restart nginx