---
# This Playbook runs all the common plays in the deployment

- name: Enable the epel repository
  shell: rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    creates=/etc/yum.repos.d/epel.repo

- name: Enable the webtactic repository
  shell: rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm
    creates=/etc/yum.repos.d/webtatic.repo

- name: Enable the remi repository
  shell: rpm -Uhv http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    creates=/etc/yum.repos.d/remi.repo

- name: Install required software
  yum: name={{ item }} state=installed
  with_items:
   - git
   - wget