---
# This Playbook will prepare to use Drupal

- name: Setup database for Drupal
  mysql_db: name={{ drupal.db_user }} state=present

- name: Setup database user for Drupal
  mysql_user: name={{ drupal.db_user }} password={{ drupal.db_pwd }} priv={{ drupal.db_name }}.*:ALL state=present

